version: "3.8"

services:
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana:Z,U
    restart: unless-stopped
    dependes_on:
      - prometheus
    networks:
      grafana-network:
        ipv4_address: 10.86.6.11

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./data/prometheus:/prometheus/data:Z,U
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:Z
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus/data'
      - '--storage.tsdb.retention.time=30d'
    restart: unless-stopped
    extra_hosts:
      - "host.containers.internal:host-gateway"
    networks:
      grafana-network:
        ipv4_address: 10.86.6.10

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter
    restart: always
    pid: host
    volumes:
      - "/:/host:ro,rslave"
      - "/sys:/host/sys:ro,rslave"
      - "/proc:/host/proc:ro,rslave"
      - "/dev:/host/dev:ro"
    command:
      - '--path.rootfs=/host'
      - '--path.sysfs=/host/sys'
      - '--path.procfs=/host/proc'
      - '--collector.rapl'
      - '--collector.netdev'
    security_opt:
      - label=disable
    networks:
      grafana-network:
        ipv4_address: 10.86.6.12

networks:
  grafana-network:
    external: true
