global:
  scrape_interval: 5m

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['10.86.6.10:9090']
  - job_name: 'node'
    static_configs:
      - targets: ['10.86.6.12:9100']
